{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-client.fullname" . }}-config
  labels:
    {{- include "mcp-client.labels" . | nindent 4 }}
data:
  config.yaml: |
    mcp_server:
      host: {{ .Values.config.mcp_server.host | quote }}
      port: {{ .Values.config.mcp_server.port }}
{{- end }}
