# Default values for mcp-server Helm chart.
# Override these with --set or a custom values file.

image:
  repository: docker.io/gabiminz/mcp_server
  tag: "6d9d594-dirty"
  pullPolicy: IfNotPresent
  # pullSecrets: [] # e.g. - name: myregistrysecret

service:
  type: ClusterIP
  port: 8000
  annotations: {}

resources: {}
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

env: {}
#  MCP_HOST: 0.0.0.0
#  MCP_PORT: 8000

config:
  enabled: true
  mcp_server:
    host: 0.0.0.0
    port: 8000

# Extra labels to add to all resources
labels: {}

# Pod annotations
podAnnotations: {}

replicaCount: 1

# Liveness/readiness probe settings
probes:
  enabled: false
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1


nodeSelector: {}
tolerations: []
affinity: {}
