apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-client.fullname" . }}
  labels:
    {{- include "mcp-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mcp-client.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mcp-client.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- range $k, $v := .Values.podAnnotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mcp-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # The client waits for stdin; keep container alive by tailing /dev/null if no TTY input.
          #command: ["python", "client.py"]
          command: ["tail", "-f", "/dev/null"]
          workingDir: /app
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- if or .Values.openai.apiKey .Values.openai.existingSecret }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.openai.existingSecret }}{{ .Values.openai.existingSecret }}{{ else }}{{ include "mcp-client.fullname" . }}-openai{{ end }}
                  key: {{ .Values.openai.secretKey }}
            {{- end }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            successThreshold: {{ .Values.probes.successThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            successThreshold: {{ .Values.probes.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.config.enabled }}
        - name: config
          configMap:
            name: {{ include "mcp-client.fullname" . }}-config
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
